### ISSUE TITLE
Test links

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit.dev#168]
It would be nice to check the validity of the URLs in the documentation.

There is a tool called [liche](https://github.com/raviqqe/liche) that can do that for HTML and MD files. (Sadly, I am not aware of anything for Python.)

We can use that in pre-commit or as a [GitHub action](https://github.com/peter-evans/link-checker) like you can see e.g. [here](https://github.com/JackMcKew/awesome-python-bytes/blob/main/.github/workflows/schedule_link_checker.yml) (the action will create an issue with the report like [here](https://github.com/JackMcKew/awesome-python-bytes/issues/20))

**Comment by csomh** [comment]
grep | curl ? :)

**Comment by lachmanfrantisek** [comment]
Does anyone want to take a look? I would close it next time stale-bot brings it to us.

**Comment by jpopelka** [comment]
Using the action config you linked should be quite effortless, I'll give it a try.
