### ISSUE TITLE
[pre-commit] hugo generation

### ISSUE THREAD

**Issue by jpopelka** [packit/packit.dev#180]
to make sure that the generation doesn't fail for some reason

Related to #178

**Comment by lachmanfrantisek** [comment]
We don't need this anymore -- Jirka solved this by using a GitHub action.

**Comment by lachmanfrantisek** [comment]
Aha, I am now reading the description properly. @jpopelka Do we still need/want this?

**Comment by jpopelka** [comment]
It would be nice, but it's so low priority that it would stale out at some point anyway I guess. So let's leave it closed.
