### ISSUE TITLE
Outdated architecture diagram

### ISSUE THREAD

**Issue by jpopelka** [packit/packit.dev#195]
There's a [dia diagram](https://github.com/packit/packit.dev/blob/master/content/packit.dia) which we [used to show on the page](https://github.com/packit/packit.dev/pull/196), but it's heavily outdated, so if we ever want to show it again, we need to update it.
Since it's just a class diagram of packit (the tool, not the service) I'd say it belongs more into packit repo than here.

**Comment by TomasTomecek** [comment]
I'd remove it completely - I don't think we can keep such diagram up to date with the changes we are doing.
