### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit.dev#197]
The installation steps are a bit outdated: https://packit.dev/docs/guide/#have-packit-tooling-installed-locally

* We don't need to enable `updates-testing` repo.
* We now have Copr projects for master and releases.

(You can look at the [README](https://github.com/packit/packit/blob/master/README.md#installation) of packit.)

**Comment by TomasTomecek** [comment]
+1 I added it to the upstream project
