### ISSUE TITLE
Usability problems in Packit documentation

### ISSUE THREAD

**Issue by pcahyna** [packit/packit.dev#203]
As a first time user with quite specific needs (multi-source RPM), I have needed to tweak lots of settings in packit, so I've needed to read the documentation in detail. I've found that it is often quite difficult to understand what it really does, which makes using all those settings difficult. Note that I am writing that without looking at the source code or without much experimenting, as in my opinion the documentation itself should be clear enough. (Some of the issues may turn into usability improvement of the code itself, but right now I am looking at them from the point of someone reading the docs.)

### [create_tarball_command](https://packit.dev/docs/configuration/#create_tarball_command)
> (defaults to git archive -o "{specfile_dir}/{package_name}-{version}.tar.gz" --prefix "{package_name}-{version}/" HEAD).
- What is `{package_name}`? upstream_package_name or downstream_package_name?
- `{version}` - is it determined by current_version_command ? If so, add a crossref. Or by get-current-version action? Why is there both current_version_command and get-current-version that seem to do the same thing, actually? This is confusing.

- How is the command related to the create-archive action? They seem similar. Is the value of `create_tarball_command` used by the default create-archive action?
- Are `{package_name}` and `{version}` some tags that can be actually used in the custom string, like in archive_root_dir_template, and packit will expand them, or are they merely placeholders for docs?
### [upstream_package_name](https://packit.dev/docs/configuration/#upstream_package_name)
> this is used in %prep section to generate an archive

unclear. What is it actually used for? Does it refer to the autosetup -n munging described in archive_root_dir_template? Or to tarball creation? Or both? And how is it used to generate an archive? And by whom is it used? By the create_tarball_command? Or by the create-archive action? Or by the fix-spec-file action? Or by all three?

### [archive_root_dir_template](https://packit.dev/docs/configuration/#archive_root_dir_template)
> Packit is updating %autosetup -n ... line in a spec file.

- What about %setup, does it concern %setup as well?
- Is it related to the fix-spec-file action?
- Does the value of archive_root_dir_template get somehow passed to the create-archive action? If not why not? This action needs to know it. Same for fix-spec-file.

> For this purpose, it requires the name of the archive root directory.

Why? It has created the package itself using create_tarball_command, so it can know itself what is the root directory. What is the relation to create_tarball_command? If I set archive_root_dir_template, will it affect both create_tarball_command and the autosetup -n munging? If not, why not?

> If packit is not able to extract it from the archive, it is possible to specify it explicitly with this option.

What archive is packit extracting it from? The archive that it has itself created? And how does packit extract it?

> You can use following tags in string: `{upstream_pkg_name}`

Why not call it `{upstream_package_name}` to be consistent with the parameter of the same name (which seems to hold the same value)?

### [How can I download RPM spec file if it is not part of upstream repository?](https://packit.dev/docs/faq/#how-can-i-download-rpm-spec-file-if-it-is-not-part-of-upstream-repository)
> `post-upstream-clone: "wget https://src.fedoraproject.org/rpms/packit/raw/master/f/packit.spec"`

That's a bad idea because wget downloads the file as packit.spec.N if the file exists (this will byte you when testing locally when there already is a spec file from previous runs). Of course the wget/curl command can be "fixed" (making it more complicated), but wouldn't it be better to be able to provide URLs in a more declarative way? Just allow an URL as a value for `specfile_path` in addition to a relative path (even rpm allows URLs in Source tags.)

### [Creating SRPM](https://packit.dev/docs/actions/#creating-srpm)
> fix-spec-file — this action performs these 3 operations on a spec file:

it is nice that it performs three actions, but what if (and this will be the typical case) I need to override only one of them and use the default implementations of the other two? Wouldn't it be better to allow overriding the three actions selectively? Could you please at least show what is the default value of this action so that one can copy it and modify only the part that one does need to modify [*]?

> You can write a simple shell script and use sed to set the new Sources correctly, e.g. `sed -i packaging/fedora/snapd.spec -e "s/https.*only-vendor.tar.xz/$correct_tarball_path/"`

This example raises more questions than answers. First, when writing the script, how do I know that packit has put the spec file under packaging/fedora/snapd.spec ? I suppose that I should replace `snapd.spec` by my spec file name, but how do I know the path? Is `packaging/fedora` some constant? (I guess that to clarify this, it would be enough to document that the script - or all the scripts - is being run with the CWD set to the root of the repository and that it is expected to modify the file in-place. I originally thought that the script gets executed in some staging directory.) And what is the `$correct_tarball_path` variable there? Is it something defined by Packit? Shouldn't I rather use the `$PACKIT_PROJECT_ARCHIVE` variable, as it seems to be documented for this purpose?

Concerning the environment variables, doesn't this action need to obtain also the expanded value of archive_root_dir_template? How can it replace %setup without knowing the name of the root?

> Replaces Source0 with a local path to the generated tarball

not necessarily, if one uses spec_source_id

> a package may define more Sources - in such a case, default implementation of fix-spec-file won’t be able to update %prep correctly.

Why not? A generic implementation should be possible, or no? (OK, I can try to implement something myself, unless you tell me that you already considered it and there is some showstopper.)

[*] I cheated and looked into the sources. Lasciate ogni speranza voi che need to reimplement all this Python in shell...

**Comment by lachmanfrantisek** [comment]
@pcahyna thanks for the really detailed feedback, we started improving our webpage recently and this can be a good input for the content.

You are right, a few of them are more about UX then about the docs itself. We can create a new issue for each of it if need. Here are my notes to a few of them. To ones that I don't have any comment are probably `:1`. If you think we need to discuss anything more deeply, we can create a new issue or [a discussion topic](https://github.com/packit/packit/discussions) to not make this issue too messy with a lot of parallel communication..;)

> create_tarball_command

Valid points. Needs to be clarified. Thanks.

> Are {package_name} and {version} some tags that can be actually used in the custom string, like in archive_root_dir_template, and packit will expand them, or are they merely placeholders for docs?

They can be used only in some template strings, not all of them. We can probably implement it in general, but would it be useful and worth spending the time?

> upstream_package_name

We can maybe do a better job in the description, but let's show a common example:
* Upstream name is `ogr` (our Python library), it's used as the GitHub project name, release archive name and directory in that archive.
* Downstream name is `python-ogr` and it's used when working with the downstream related tools like pagure, koji, copr,...

> Does the value of archive_root_dir_template get somehow passed to the create-archive action? If not why not? This action needs to know it. Same for fix-spec-file.

No, we haven't got any request to do so. I am not sure why you need that and maybe it's not clear why it is needed:
* It's a name of the directory in the source archive. Not the archive.
* We need to get it correctly because of the `autosetup -n` line. (Some projects use an upstream name, some others downstream.)
* For tar archives with one directory, we get it automatically.
* Otherwise, we use `{upstream_pkg_name}-{version}` (used before adding this option as the only way).
* Why would you need that value. You can use anything and place here the template.

> What archive is packit extracting it from? The archive that it has itself created? And how does packit extract it?
* We work with only a single archive, archive with the sources.
* Yes, but we don't know about the content/structure of that archive. We use `git archive` as default, but you can use anything.
* We use tar python module -- we only support this. Yes, it can be added to the docs.

> How can I download RPM spec file if it is not part of upstream repository?

Good point. Users with this option use that in service mostly where this problem can't occur.
We discuss this specfile problem multiple times and agreed on not supporting  (=don't like too much..;) that workflow but still provide some option for those users. I think we can fix the example command -- It can be solved really quickly. We have a really big backlog and need to carefully pick the most important taks.) But if it's really important to you, we can think about adding the `specfile_url` or being able to add URL to `specfile_path`.

> Creating SRPM

I hope it's better to improve the content of docs directly hen writing you the answers here.

Thanks again a lot for all the questions. I haven't answered all of them -- if you need some question now, let me/us know. Otherwise, it will be a task for someone from the team to improve the docs so you don't need to ask..,;)

**Comment by pcahyna** [comment]
@lachmanfrantisek thank your for your interest and your reply. Some of the points may be misunderstandings of what I complained about, so I will try to clarify:

> > create_tarball_command
> >
> > Are {package_name} and {version} some tags that can be actually used in the custom string, like in archive_root_dir_template, and packit will expand them, or are they merely placeholders for docs?
> 
>    * They can be used only in some template strings, not all of them. We can probably implement it in general, but would it be useful and worth spending the time?

Sorry if this was understood as a request to implement those tags in more places, that was not what I intended. My problem is that if I see a string with replaceable tags like those, I can interpret it in two ways:
* As a user, I am supposed to replace the tag with a concrete value and put it there. The tag is used merely as a placeholder in docs.
* I can use the tag literally and the software will replace it by the appropriate value when needed (the tag represents a variable or macro).

In archive_root_dir_template, it is obvious that the second interpretation was intended, because the documentation reads: 
> You can use following tags in string:
>
>    {upstream_pkg_name} - upstream package name
>    {version} - package version

In create_tarball_command, no such explanation is given, so it is not clear that one can actually use the tags in the string. One can only guess by analogy with archive_root_dir_template that probably yes, but one can't be sure. Especially because the description of archive_root_dir_template comes after create_tarball_command, so while reading about create_tarball_command one does not know it yet.

IMO, each configuration value that accepts replaceable tags should have an explanation like the one above: "You can use following tags in string: - {a}  - {b}" . Or, at the beginning of the document, you can supply a generic explanation like "In some configuration strings you can use tags enclosed in curly braces and Packit will substitute the appropriate values. The tags allowed in each string, if any, are shown in the description of the top level key." and you don't have to repeat "You can use following tags in string" every time.

> > upstream_package_name
> 
>    * We can maybe do a better job in the description, but let's show a common example:
>       
>      * Upstream name is `ogr` (our Python library), it's used as the GitHub project name, release archive name and directory in that archive.
>      * Downstream name is `python-ogr`, and it's used when working with the downstream related tools like pagure, koji, copr,...
> 

I understand what is upstream_package_name, I don't understand where is Packit using the value, because the description "this is used in %prep section to generate an archive." is unclear. First of all, the %prep section in specs is not used to generate archives but to unpack them. So, what exactly is upstream_package_name used for? Packit transforms the %setup (or %autosetup) macro in %prep and adds -n, according to the description of fix-spec-file. So, is upstream_package_name used for that? Or for something else?

> 
> > Does the value of archive_root_dir_template get somehow passed to the create-archive action? If not why not? This action needs to know it. Same for fix-spec-file.
> 
>    * No, we haven't got any request to do so. I am not sure why you need that, and maybe it's because it's not clear why it is used/needed:
>       
>      * It's a name of the directory in the source archive. Not the archive.
>      * We need to get it correctly because of the `autosetup -n` line. (Some projects use an upstream name, some others downstream.)
>      * For tar archives with one directory, we get it automatically.
>      * Otherwise, we use `{upstream_pkg_name}-{version}` (used before adding this option as the only way).
>      * Why would you need that value. You can use anything and place here the template.

I can use anything, sure, but then I need to customize my archive creation command (the create-archive action (or is that the create_tarball_command? (or both? ) ) ) to create the appropriate directory. E.g. if my top level directory is named `myweirddir`, I have to set `archive_root_dir_template` to `myweirddir` and at the same time set create_tarball_command to something like `git archive ... --prefix "myweirddir/" HEAD` in order to create what archive_root_dir_template expects (forgetting for the moment that Packit would be able to figure out the root directory automatically in this simple example). So, I have to specify `myweirddir` twice. And if I want to change it to `otherweirddir`, I have to change it at both places. This is a bit silly, because if one provides this value once, one expects the software to use it at other places where it is required to be consistent. (I don't have any use for this at the moment, so maybe it is just a theoretical concern and it never occurs in practice, it just struck me as an inconsistency while reading the docs. But since you can extract the directory only from tar files, every time another archive format is used, one would probably hit it.)

> > What archive is packit extracting it from? The archive that it has itself created? And how does packit extract it?
> 
>    * We work with only a single archive, archive with the sources.
> 
>    * Yes, but we don't know about the content/structure of that archive. We use `git archive` as default, but you can use anything.

OK, it sounded silly that Packit must look into the archive to discover the name of the top level directory that Packit put itself there and presumably forgot about it, but since there can be anything, it makes more sense.

OTOH, if `archive_root_dir_template` were better coordinated with `create_tarball_command`, as I suggest above, there would be no need to extract the top lever dir from the archive, because Packit would know it. (Isn't the extraction from archive slow for huge archives? I don't care, my projects are small.)

>    * We use tar python module -- we only support this. Yes, it can be added to the docs.

It could - the main thing that was unclear in the docs is that Packit extracts it from the archive that it has just created.

> > How can I download RPM spec file if it is not part of upstream repository?
> 
>    * Good point. Users with this option mostly use that in service where this problem can't occur.

The guide instructs me to have everything working locally first and worry about the sevice later :-)

>    We've discussed this specfile problem multiple times and agreed on not supporting  (=don't like too much..;) that workflow but still provide some option for those users. 

It is required in multi-source RPMs where you want to trigger Packit builds on changes of every source repo, not just the main one that has the spec file, right? Unless you want to copy the spec to all the repos and keep it in sync (this is even a worse option than downloading it with wget). Or is there some other option for this?

> I think we can fix the example command -- It can be solved really quickly. We have a huge backlog and need to pick the most important tasks carefully.) But if it's essential to you, we can think about adding the `specfile_url` or being able to add URL to `specfile_path`.

I can have a look at implementing this when I have some spare cycles....

> > Creating SRPM
> 
>    * I hope it's better to improve the content of docs directly hen writing you the answers here.
> 
> 
> Thanks again a lot for all the questions. I haven't answered all of them -- if you need some question now, let me/us know. Otherwise, it will be a task for someone from the team to improve the docs in a way that you don't need to ask..,;)

Oh sure - I don't ask the questions to discover the answer myself (in the case where I really needed the answer, I looked into the source), but to point out that the documentation is not clear or that the consistency of the UX could be improved. If you have suggested documentation changes, I will be happy to review them.

**Comment by lachmanfrantisek** [comment]
Thanks for the response. A think a lot of the points can be solved one-by-one.

A few responses:

> OTOH, if archive_root_dir_template were better coordinated with create_tarball_command, as I suggest above, there would be no need to extract the top lever dir from the archive, because Packit would know it. (Isn't the extraction from archive slow for huge archives? I don't care, my projects are small.)

If it helps, we can provide an environment variable for that purpose. We already do that and it's not hard to do. It's just that people usually reuse existing commands (often some make target) and the naming, structure and format of the archive can be anything. And we need to get some extra information to play nicely with that.

> The guide instructs me to have everything working locally first and worry about the sevice later :-)

Sure. That's why I wrote "Good point" -- we need to fix that... (That was only a small excuse why we haven't caught that already...;)

> I can have a look at implementing this when I have some spare cycles....

Thanks. That would be great. With our limited resources, we would probably stick with better command for downloading.

> Oh sure - I don't ask the questions to discover the answer myself (in the case where I really needed the answer, I looked into the source), but to point out that the documentation is not clear or that the consistency of the UX could be improved. If you have suggested documentation changes, I will be happy to review them.

Thanks a lot. I hope someone will take a look and ping you on the PR. (You can also send the PR for some parts yourself if you really really want and have some spare time..;)

**Comment by TomasTomecek** [comment]
@pcahyna thank you so much for such a wonderful write-up and feedback. We believe those are now addressed in the documentation, so I am going to close this one.

If you have further suggestions or questions, don't hesitate to reach out, we love hearing feedback like this one :)
