### ISSUE TITLE
Landing page is too fussy/boring

### ISSUE THREAD

**Issue by jpopelka** [packit/packit.dev#217]
https://github.com/packit/packit.dev/pull/212#issuecomment-756752829

[Tomas] I'd love to improve the landing page to be more appealing - ideally show some diagram so people are not overwhelmed with lots of text initially.

[Jirka] Yeah, I was thinking about it too. What about (for now) just moving [The key principles of packit](https://packit.dev/#the-key-principles-of-packit) and [Why packit?](https://packit.dev/#why-packit) someplace else. Ideas where?

**Comment by TomasTomecek** [comment]
@jpopelka I'd probably create a subpage for those - how about having an "About" page?
