### ISSUE TITLE
Update Testing Farm docs after API migration

### ISSUE THREAD

**Issue by csomh** [packit/packit.dev#238]
Some things changed with the new API. Document those.

Probably related to #64, too.

**Comment by TomasTomecek** [comment]
@psss would you be interested in updating the documentation?

**Comment by psss** [comment]
Looking at https://packit.dev/docs/testing-farm/ I see the `tmt` part is already covered and up-to-date. There are no changes in that respect, right, @thrix? The worker section, however, will need an update. That part would be rather for @thrix, I guess.

**Comment by jpopelka** [comment]
> The worker section, however, will need an update.

I removed it in [#257](https://github.com/packit/packit.dev/pull/257/files#diff-b0504737be4eaa40236ac9c43d052a581cd52939d73139c1351437d76d122570L337)

I think this issue can be closed, please re-open if you think otherwise.
