### ISSUE TITLE
Mention `Namespace is not allowed` in FAQ linked from the service

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit.dev#297]
We link [FAQ](https://packit.dev/docs/faq/#can-i-use-the-packit-service-as-soon-as-i-install-it-into-my-repository) when user gets `Namespace is not allowed` error.

It would be nice to:
- [ ] mention the error message in the paragraph
- [x] link and describe the issues in the notification's repo (https://github.com/packit/notifications/issues)

**Comment by hroncok** [comment]
I believe this is still relevant.

**Comment by hroncok** [comment]
Don't

**Comment by hroncok** [comment]
As always, your bot acts in a hostile way. Please, don't.

**Comment by lachmanfrantisek** [comment]
@hroncok Sorry about the mess (and bot). We have already improved this in https://github.com/packit/packit-service/pull/1308 (the issue message) and https://github.com/packit/packit.dev/pull/367 (the FAQ paragraph).

I hope it's better now and going to fix the last point and mention the `Namespace is not allowed`.
