### ISSUE TITLE
Create user docs on how to use Git trailers for patch metadata

### ISSUE THREAD

**Issue by csomh** [packit/packit.dev#323]
This is to document the changes introduced in packit/packit#1336.

Explain how Git-trailers can be used to influence how patches are generated and added to the spec-file when updating a dist-git repo from a source-git repo.

Explain how this patch-metadata is used during initializing a source-git repo, so that when the same content is synced back produces no or minimal changes in dist-git.

**Comment by TomasTomecek** [comment]
as part of this, we could also update the `packit source-git init` document

**Comment by csomh** [comment]
> as part of this, we could also update the `packit source-git init` document

see #322

**Comment by TomasTomecek** [comment]
> > as part of this, we could also update the `packit source-git init` document
> 
> see #322

sorry, missed that one
