### ISSUE TITLE
Document and add examples for `skip_build`

### ISSUE THREAD

**Issue by csomh** [packit/packit.dev#355]
It was implemented in packit/packit-service#1256.

**Comment by lachmanfrantisek** [comment]
@lbarcziova has wanted to test this for some time before docs and announcement if I recall correctly... But good to track this somewhere.

**Comment by lbarcziova** [comment]
There is already opened a PR for this: #352

**Comment by csomh** [comment]
> There is already opened PR for this: #352

Apologies, I checked only on packit.dev, but did not check open PRs in this repo. Closing it then.

Thanks for keeping docs up to date! :smiley:
