### ISSUE TITLE
Front page improvements

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit.dev#386]
As @xsuchy suggested, our front page needs some care:

* Provide a clear description of what Packit is.
* Shortly show what we can provide to our users (selling points).
* => Everything required for the decision if Packit is the right tool for someone (and they want to use it) is on the front page.

**Comment by TomasTomecek** [comment]
Please include a diagram or an image/screenshot :)

**Comment by pirat89** [comment]
I am starting to feel guilty, but I really think the docs should be improved :)

**Comment by lbarcziova** [comment]
Yes, forgot to reference it, but this was implemented in #413.

**Comment by pirat89** [comment]
That's great! Thank you guys you are working on that!
