### ISSUE TITLE
Show realtime statistics in our frontpage

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit.dev#417]
- some ideas:
    - number of Copr builds today/this week
    - number of tests run today/this week
    - ...
    
TODO (needs to be researched first):
- [ ] get the numbers (e.g. reuse current metrics in workers.packit.dev/metrics)
- [ ] visualize them

**Comment by TomasTomecek** [comment]
nice!

I guess the easiest way to do this would be to write client side javascript code to pick the numbers from worker.p.d/metrics endpoint, process and visualize them

**Comment by lachmanfrantisek** [comment]
Based on the research (https://github.com/packit/research/tree/main/adoption-metrics) , it will be hard to do directly. Once we have the charts elsewhere we can think about a way how to show this on our homepage. Let's close this issue since we will not work on this soon.
