### ISSUE TITLE
[config] 'create_tarball_command:' vs. 'actions: create-archive:' 

### ISSUE THREAD

**Issue by jpopelka** [packit/packit.dev#48]
[create_tarball_command: doc](https://packit.dev/docs/configuration/#top-level-keys) says: "a command which generates upstream tarball in the root of the upstream directory"
[actions: create-archive: doc](https://packit.dev/docs/actions/#creating-srpm) says: "when the archive needs to be created"

What's the difference (between tarball and archive)?

EDIT: Another point is that `actions: create-archive:` is supposed to be used in [propose-update](https://packit.dev/docs/actions/#propose-update-command) and [srpm/copr-build](https://packit.dev/docs/actions/#creating-srpm), but looking at the code I see it only in [API.create_srpm()](https://github.com/packit-service/packit/blob/master/packit/api.py#L481) not in [API.sync_release()](https://github.com/packit-service/packit/blob/master/packit/api.py#L143)

**Comment by TomasTomecek** [comment]
so what's the work here?

**Comment by jpopelka** [comment]
The work here is to answer my question.

What's the difference between `create_tarball_command` and `create-archive`?

**Comment by TomasTomecek** [comment]
create_tarball_command: a command to use to create a tarball, instead of our git archive - this may be pretty tricky since people don't know what's the name of the archive meant to be
create-archive: an action which is suppose to replace more packit behaviour (and output the archive path). But when I look at the code right now, it doesn't make sense since both the action and the create_tarball_command are called - we should clean that up

**Comment by lachmanfrantisek** [comment]
>  we should clean that up

:+1: 

The `create_tarball_command` was there before actions were supported.

**Comment by lachmanfrantisek** [comment]
What about moving this to packit repo if we want to deprecate that?

As @TomasTomecek wrote, they cannot be replaced as is. Since the behaviour differs a bit.

**Comment by lbarcziova** [comment]
While updating the docs, I checked the Packit code and:
1. The workflow for creating an archive:

- if there's defined the `create-archive` action, we run it, then go through the output, try to parse the archive path from it and possibly create a relative symlink to the archive from in the specfile directory
- else we use the `create_tarball_command`; we construct the archive path as `{package_name}-{version}.tar.gz` and expect it to be created in the directory with the specfile and then run the command, which defaults to `git archive -o "{specfile_dir}/{package_name}-{version}.tar.gz" --prefix "{package_name}-{version}/" HEAD`, we don't check the output, just return the constructed archive path. So if I understand correctly we expect the `create_tarball_command` defined by user also to create archive `{package_name}-{version}.tar.gz` (but haven't found this mentioned in the docs)... 

I would say this is confusing, IMHO it would make sense to have just `create-archive`  action and our `git archive..` command as a fallback when no action defined.

2. 
> EDIT: Another point is that actions: create-archive: is supposed to be used in propose-update and srpm/copr-build, but looking at the code I see it only in API.create_srpm() not in API.sync_release()

You're right, I will remove the create-archive from propose-update docs.

**Comment by lachmanfrantisek** [comment]
@lbarcziova agree. Thanks for looking into that. What about deprecating `create_tarball_command` then? (And removing a few versions later.)

**Comment by lbarcziova** [comment]
+1 for deprecating it, will create an issue for it...And now I found out there is a similar situation with the `get-current-version` action and `current_version_command`, can we do it as well (leaving just the action)?

**Comment by lachmanfrantisek** [comment]
Still valid.

**Comment by mfocko** [comment]
Isn't this fixed by deprecating `create_tarball_command`?

**Comment by jpopelka** [comment]
I think so, yes, thanks.
