### ISSUE TITLE
Document 'tmt_plan' and 'tf_post_install_script'

### ISSUE THREAD

**Issue by csomh** [packit/packit.dev#491]
Was introduced in packit/packit#1619.

**Comment by TomasTomecek** [comment]
ah, I just realized Rodolfo already resolved this in https://github.com/packit/packit.dev/pull/489

pity he didn't link the docs PR with the p-s PR

**Comment by TomasTomecek** [comment]
oh, I missed it's in the testing-farm document and not the configuration; agreed!

**Comment by TomasTomecek** [comment]
There are only links in configuration.md pointing to testing-farm. Do we want to keep this trend or actually have a single page with all the configuration values?

**Comment by csomh** [comment]
I'm not sure, but so far I found it handy to be able to open the configuration page and look up any configuration option.

As a user I would expect something like this, or if there are more options, then maybe multiple pages, but then it should be clear which page covers what. Right now I don't think it's self-explanatory that the "Testing Farm" page also documents configuration, or that the Configuration page doesn't document options related to Testing Farm.

**Comment by TomasTomecek** [comment]
+1 I also `grep` mostly when looking for a config option

**Comment by lachmanfrantisek** [comment]
Related to #467

**Comment by csomh** [comment]
Closing. #467 should fix this.
