### ISSUE TITLE
Create a blog-post about pull-from-upstream workflow

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit.dev#496]
Finalise the packit/packit-service#1576 epic by creating a blog post about it. Describe how it works, how to set it up and provide some screenshots and links to the configuration.

*part of packit/packit-service#1576 epic*

**Comment by xsuchy** [comment]
I have written
http://miroslav.suchy.cz/blog/archives/2022/07/14/packit_-_how_to_create_pull-request_for_fedora_from_upstream/index.html  Can we use it as is? Or write it more generally?

**Comment by lachmanfrantisek** [comment]
@xsuchy sorry for the late response but this is about another workflow we are currently finishing (https://github.com/packit/packit-service/issues/1576). This is to configure Packit in dist-git and "pull" the new version from upstream instead of current "push" approach of `propose-downstream` workflow.

(But the core functionality is shared between those two.)
