### ISSUE TITLE
Name our weekly 

### ISSUE THREAD

**Issue by xsuchy** [packit/packit.dev#500]
When we name our weekly update, this is how it shows in most aggregators:
![Screenshot_20220714_125519](https://user-images.githubusercontent.com/85769/178967188-0c8bfe8b-5fd1-4b38-9c20-1ea0ab9de705.png)

It is not clear what `July 2022` is about. Notice how CPE does that: CPE Weekly Update – Week 27 2022

Can we name it e.g., Packit in July 2022?

**Comment by lachmanfrantisek** [comment]
We are speaking about this, aren't we?
https://github.com/packit/packit.dev/blob/626055f2a648ea3376c4d7b870d1d1de2aa69ab3/content/posts/weekly/June-2022.md?plain=1#L2

This will result in  `Packit in July 2022 | Packit` titles for the webpage but that's not a huge issue.

**Comment by lachmanfrantisek** [comment]
And one thing, do you receive updates every week or just for the first week in a month?

(Since we create a new page for the whole month when adding the first week of a month and update the existing page for other weeks in a month.)

**Comment by xsuchy** [comment]
See https://packit.dev/posts/weekly/
And once published the new one, you can see it live on http://fedoraplanet.org/

**Comment by jpopelka** [comment]
Maybe there's a way how to [tweak just the RSS feed content](https://gohugo.io/templates/rss/) without us having to change the existing layout?

**Comment by lachmanfrantisek** [comment]
> See https://packit.dev/posts/weekly/

You mean [this](https://packit.dev/posts/weekly/index.xml)? It looks like there is always just a first week of each month...

> And once published the new one, you can see it live on http://fedoraplanet.org/

I can't see any Packit article there (the oldest available is from August 11). So it looks like we really publish just a first week monthly.

**Comment by TomasTomecek** [comment]
We concluded we will name the next one "Packit [in] January 2023".

**Comment by lbarcziova** [comment]
We changed the naming to `Week X in Packit`.
