### ISSUE TITLE
Create a troubleshooting guide/section

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit.dev#519]
Some problems happen often to our users and the solution needs to be reinvented again and again. What about describing usual issues/problems/errors and their solution?

This can be very related to #415 that is targeted to the final use case, but here I would like to see a few example warnings/errors, what they mean and how to fix them when configuring Packit.

**Comment by TomasTomecek** [comment]
Related: https://github.com/packit/packit-service/issues/1657
