### ISSUE TITLE
Docs unclear on which branch with config file is used for what

### ISSUE THREAD

**Issue by VladimirSlavik** [packit/packit.dev#522]
URL: https://packit.dev/docs/configuration/

I can read the following on this page:

> Packit uses a configuration file in the upstream repository.

> You should place the file in the root of your upstream repo.

> When you open a pull request against your upstream repository, packit service picks up configuration file from your pull request, not from the branch against the PR is opened.

However, none of this tells me:

- If any of the various jobs are used depending on the branch where the file is
- Which parts of the config file are "taken from pull request" and used for things done with that pull request
- Which parts of the file from which branch are used when I add a new release
- If I can create a combination of some kind of job / defined on which branch / with whatever unknown keys under "job" ... to actually propose a downstream release, only to branched fedora

**Comment by VladimirSlavik** [comment]
Based on irc conversation, my understanding is:
- packit takes the config file from the commit/sha "associated" with the event that triggered packit
- parts of config that aren't jobs are taken as is
- the jobs are "filtered" according to the event type and branch (specified for each job in the config)
- the remaining jobs (matching the event and branch) run

**Comment by VladimirSlavik** [comment]
Why, thank you.

**Comment by TomasTomecek** [comment]
Sorry for the lack of response, we completely forgot to reply.

Sounds like it would be best to sit down and talk about how we should improve our documentation so it's more clear :)
