### ISSUE TITLE
Document how to check binary RPMs with Testing Farm

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit.dev#607]
Follow up to https://github.com/packit/packit.dev/issues/601

Blocked on:
- https://gitlab.com/testing-farm/general/-/issues/65
- https://issues.redhat.com/browse/TFT-1574

[rpminspect allows analyzing binary RPMs](https://github.com/packit/packit.dev/pull/604#issuecomment-1434271660) and that's how it runs on dist-git. Let's document how to do this with Packit and Testing Farm once the RPM files are available in the testing environment.

(we could download them ourselves in theory but if this is what TF is meant to do, let's do it the right way)

**Comment by lbarcziova** [comment]
The latest release of TF should now unblock this, so we can test this out and document it.

**Comment by LecrisUT** [comment]
Also, one thing to consider. How about making these tests reusable so that they can be imported? E.g.:
```
plan:
    import:
        url: https://github.com/packit/packit
        name: /rpmlint
```

**Comment by lachmanfrantisek** [comment]
Good point from @LecrisUT about the shared "library" for such tests.
