### ISSUE TITLE
Documentation is missing epel targets

### ISSUE THREAD

**Issue by psss** [packit/packit.dev#63]
The [configuration page](https://packit.dev/docs/configuration/) shows a few examples of copr targets but I was not able to find how epel should be enabled. Please include a list of all available targets or at least add an epel example. Thanks.

**Comment by TomasTomecek** [comment]
I think it would be nice to show all the x86_64 targets in the docs since we cannot easily link to such copr page with all the available chroots.

**Comment by psss** [comment]
What would be the best place for the list? Perhaps the configuration page?
https://packit.dev/docs/configuration/

**Comment by jpopelka** [comment]
Yes, probably the configuration page.

**Comment by lachmanfrantisek** [comment]
Maybe a relevant topic, if you use outdated/bad target, we put a full list of all supported targets into the comment. (thanks to @mfocko )

More relevant question(s):
- Do we have some idea about how we want to update it?
  - With aliases, this can be static. (We have aliases for Fedora only.)

**Comment by lachmanfrantisek** [comment]
Hey, stale-got! Why did you close that?
