### ISSUE TITLE
Testing docs need improvement

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit.dev#64]
1. The document says to run `fmf init`. I did that and got .fmf directory instead of ci.fmf which the document describes, what should I do?
Answer: `fmf init` is required for fmf to work in the repo; then the *.fmf file needs to be placed somewhere within the repo, NOT inside .fmf

2. How are the tests executed? Are all the tests executed on one node or in parallel on multiple ones? In which order?

3. Should I define one prepare step or multiple ones?

4. How can I define vars for my prepare playbook?
 * RFE: https://gitlab.com/testing-farm/general/issues/4

5. more examples

**Comment by TomasTomecek** [comment]
@thrix @psss FYI

**Comment by psss** [comment]
Once the migration from cruncher to testing farm is completed the documentation/steps for enabling tests will be basically identical with Fedora CI. We could point users to the [tmt page](https://docs.fedoraproject.org/en-US/ci/tmt/) there.

**Comment by thrix** [comment]
Migration from cruncher is happening soon, keeping open
