### ISSUE TITLE
Blogpost about %autorelease

### ISSUE THREAD

**Issue by xsuchy** [packit/packit.dev#643]
### Description

Please write a blogpost about %autorelease feature we recently finished.

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by nforro** [comment]
I think we could mention what was fixed and describe [the logic](https://github.com/packit/packit/blob/9ce4c0198250603835e720702bd4fc88b978c215/packit/base_git.py#L394-L420) behind synchronizing `Release`, even though it should be pretty intuitive.
