### ISSUE TITLE
supported triggers vs. jobs - matrix

### ISSUE THREAD

**Issue by dhodovsk** [packit/packit.dev#66]
Make it more obvious what jobs can be triggered by which events by adding into doc a table:

For example:

  | commit | pull_request | release
-- | -- | -- | --
copr_build | - | :heavy_check_mark: | :heavy_check_mark:
tests | :heavy_check_mark: | - | -
propose_downstream | - | - | :heavy_check_mark:

**Comment by TomasTomecek** [comment]
looks lovely!

**Comment by lachmanfrantisek** [comment]
That would be nice!

**Comment by lachmanfrantisek** [comment]
Hey, stale-got! Why did you close that?

**Comment by lachmanfrantisek** [comment]
Still relevant I think.
