### ISSUE TITLE
Enable copy_upstream_release_description for non-Github repositories

### ISSUE THREAD

**Issue by ljavorsk** [packit/packit.dev#661]
### Description

The `copy_upstream_release_description` action is Github exclusive (as mentioned in https://github.com/packit/packit.dev/pull/656#issuecomment-1571987583), but a lot of upstreams have their git repositories at other places like Gitlab, Salsa.debian,...

Could you please expand this action to other git remote repositories as well?

### Benefit

Could be used in more packages

### Importance

Low

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by mfocko** [comment]
Do you have an example of it not working? I had a look at the code and it doesn't seem to care about the forge (though will scream in pain on Pagure…)

**Comment by ljavorsk** [comment]
I don't, I only asked in this https://github.com/packit/packit.dev/pull/656#issuecomment-1571926204 to verify if it's working and I was told to file an issue, because it may not work properly.

Do you have any experience with different forges?

**Comment by mfocko** [comment]
I was testing propose-downstream on GitLab and it worked (afterwards we broke it and fixed it :D), so it should be fine IMO (especially since the biggest issue is Pagure that doesn't support releases at all **and** we don't support it for upstream).

I was looking for this issue yesterday and couldn't find it, cause I didn't expect it in the docs, but in case I'm right and it works, you actually filed it in the correct place, cause we just need to adjust the docs :)

**Comment by mfocko** [comment]
Checked locally just the part that gets the changelog, and it looks fine

Reproducer:
```py
#!/usr/bin/env python3

from ogr import GitlabService


def main():
    gs = GitlabService(instance_url="https://salsa.debian.org")
    p = gs.get_project(namespace="manpages-l10n-team", repo="manpages-l10n")

    r = p.get_release(tag_name="4.19.0", name="Release 4.19.0")
    print(r.body)


if __name__ == '__main__':
    main()
```

Produced changelog:
```
Besides new and updated translations (as usual), this is a bugfix release which avoids file conflicts with util-linux-2.39. This version of util-linux has man page translations enabled by default, that's why it was needed to remove packages like util-linux*, libuuid, libblkid etc. from our lists. Currently, this only affects Fedora Rawhide, but other distributions will follow soon. The util-linux man pages are currently disabled in Archlinux, Mageia Cauldron, Fedora Rawhide and Opensuse Tumbleweed.
```

I'd be a bit careful though, cause this “form” of changelog doesn't adhere to the [packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/#changelogs).
