### ISSUE TITLE
Github Actions to generate/deploy site to GitHub Pages

### ISSUE THREAD

**Issue by jpopelka** [packit/packit.dev#78]
Rebasing PRs are pain due to the generated HTML code.
If we could generate the result code after merging into master that would be much nicer.

There are already some existing Github Actions for this:
https://github.com/marketplace?type=actions&query=Hugo

**Comment by csomh** [comment]
Another way to go would be to switch to [Jekyll](https://jekyllrb.com/). [GitHub integrates with Jekyll](https://help.github.com/en/github/working-with-github-pages/setting-up-a-github-pages-site-with-jekyll), so it would regenerate the site on new commits.

**Comment by csomh** [comment]
One more idea: just move this repo to gitlab.com, which has support for hugo.

Will need some tweaking (for example cleaning up the docs directory from generated content), and every team member will need to create a gitlab.com account (can be done with a GitHub account), but in exchange we will have very easy to read PRs.

Custom domain is supported, so there wouldn't be any change from a user POV.

**Comment by lachmanfrantisek** [comment]
I am ok with GitLab. (It can only be confusing to others that some repos are here and something on gitlab.)

What about syncing this repo to GitLab and let the GitLab make the generation with hugo..;)

**Comment by csomh** [comment]
> What about syncing this repo to GitLab and let the GitLab make the generation with hugo? (I am only a little worried about delays with the whole workflow.)

This sounds genius :) We could give it a try to have an understanding of the delay. But we talk about a (static) website, so some delay is acceptable.

**Comment by TomasTomecek** [comment]
I'd try actions first
