### ISSUE TITLE
Write a blog post about downstream jobs targeting Fedora package maintainers

### ISSUE THREAD

**Issue by nforro** [packit/packit.dev#802]
We do have [Fedora releases guide](https://packit.dev/docs/fedora-releases-guide) but Fedora maintainers are still getting confused by seeing upstream jobs mentioned. Write a blog post that:

- [ ] demonstrates a basic configuration (`pull_from_upstream`, `koji_build`, `bodhi_update`) in dist git
- [ ] explains how to verify the config with CLI, how to test/run locally
- [ ] explains how/when the jobs are triggered by the service, how to trigger them manually
- [ ] explains `issue_repository`
- [ ] does not mention `propose_downstream` or any other upstream jobs

As a bonus:
- [ ] explains why `upstream_project_url` is needed (and `upstream_tag_template`)

**Comment by lbarcziova** [comment]
I would lean towards having this as a part of "regular docs" and not a blogpost, probably as a subsection of Fedora releases guide.

**Comment by nforro** [comment]
Making it part of the docs definitely makes sense, a blogpost was just the first thing that came to mind.
